# Generated by Django 4.2.9 on 2025-11-07 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("parcels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_parcels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["tracking_number"], name="parcels_trackin_6efce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(fields=["status"], name="parcels_status_ed18a4_idx"),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(fields=["customer"], name="parcels_custome_be9418_idx"),
        ),
    ]
