# Generated by Django 4.2.9 on 2025-11-08 00:57

import apps.parcels.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="clearance_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="parcel",
            name="clearance_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="customs_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="parcel",
            name="customs_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline before parcel returns to sender",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="delivery_code",
            field=models.CharField(
                default=apps.parcels.models.generate_delivery_code, max_length=6
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="delivery_code_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="parcel",
            name="delivery_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="driver_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="parcel",
            name="driver_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="parcel",
            name="driver_photo",
            field=models.ImageField(blank=True, null=True, upload_to="drivers/photos/"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="kyc_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="kyc_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="package_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="parcel",
            name="parcel_photo",
            field=models.ImageField(blank=True, null=True, upload_to="parcels/photos/"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="receiver_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="parcel",
            name="receiver_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="parcel",
            name="receiver_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="parcel",
            name="receiver_phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="parcel",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Shipping"),
                    ("express", "Express Shipping"),
                    ("overnight", "Overnight Delivery"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned to Courier"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("held_at_customs", "Held at Customs"),
                    ("awaiting_clearance", "Awaiting Clearance"),
                    ("payment_required", "Payment Required"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("failed_delivery", "Failed Delivery Attempt"),
                    ("return_to_sender", "Return to Sender"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="tracking_number",
            field=models.CharField(
                default=apps.parcels.models.generate_tracking_number,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["delivery_code"], name="parcels_deliver_305828_idx"
            ),
        ),
    ]
