# Generated by Django 4.2.9 on 2025-11-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="payments/screenshots/"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("shipping", "Shipping Fee"),
                    ("customs", "Customs Fee"),
                    ("clearance", "Clearance Fee"),
                    ("delivery", "Delivery Fee"),
                    ("insurance", "Insurance Fee"),
                    ("storage", "Storage Fee"),
                ],
                default="shipping",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof_of_payment",
            field=models.ImageField(
                blank=True, null=True, upload_to="payments/proofs/"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="thank_you_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paystack", "Paystack"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("under_review", "Under Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
